# Generated by Django 5.0 on 2023-12-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdata',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('prid', models.IntegerField()),
                ('prquantity', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
