# Generated by Django 4.2.7 on 2023-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_cartdata_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('cart_data', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cartdata',
        ),
    ]
