# Generated by Django 4.2.7 on 2023-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orders_delete_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Credit Card'), ('cash', 'Cash'), ('upi', 'UPI Payments')], default='cash', max_length=20),
        ),
    ]
