# Generated by Django 5.0 on 2024-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.CharField(default='kilogram', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
